# Generated by Django 4.2.30 on 2026-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
