# Generated by Django 4.2.30 on 2026-05-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_time_spent_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_note',
            field=models.TextField(blank=True),
        ),
    ]
